spring:
  profiles:
    active: dev   #dÃ©finir le profil actif

---
spring:
  config:
    activate:
      on-profile: dev
greeting:
  message: "ğŸ‘©â€ğŸ’» Bonjour depuis le profil DEV !"

---
spring:
  config:
    activate:
      on-profile: prod
greeting:
  message: "ğŸš€ Bonjour depuis le profil PROD !"
